### ISSUE TITLE
setup/install packages for project

### ISSUE THREAD

**Issue by KazMat1** [KazMat1/kazule-log#1]
## Todo

- [x] install breeze for setting up of inertia.js with react
- [x] install laravel-admin
- [x] add phpMyAdmin in docker container
- [x] install  tailwindcss
