### ISSUE TITLE
feature/implement contact and notification

### ISSUE THREAD

**Issue by KazMat1** [KazMat1/kazule-log#7]
## Todo
- [ ] implement contact logic 
- [ ] implement notification logic
- [ ] create a template for sending a reply email
